spring:
  datasource:
    url: jdbc:mysql://d1.nobidev.com:9236/bank-db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: e-bank
    password: 'EB@nk'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000
